### ISSUE TITLE
Default parameters in derive_key function

### ISSUE THREAD

**Issue by dederer** [KSDaemon/wampy-cra#4]
Hi, some browsers still do not support default parameters from ES6/ES2015. In my case, it's Safari 9.

    30: function derive_key (secret, salt, iterations = 1000, keylen = 32) {
                                                     ^^^
            Unexpected token '='. Expected a ')' or a ',' after a parameter declaration.

**Comment by KSDaemon** [comment]
Hi @dederer! I think, you are using es6 code from src/ folder. Just switch to build/wampy-cra.js, which works in all enviroments/browsers! ;)

**Comment by dederer** [comment]
Ah... thanks!

I import `wamp-cra` using:

    const wampyCra = require('wampy-cra');

In the file `wampy-cra/package.json` the primary entry point is `src/wampy-cra.js`. Maybe you should change the main field to:

    11: "main": "build/wampy-cra.js",

**Comment by KSDaemon** [comment]
Good point! Fixed!
